### ISSUE TITLE
Erro no windows 10 utilizando o WSL como backand no Docker "Error response from daemon: path /home/user/project_path/docker/nginx is mounted on / but it is not a shared mount."

### ISSUE THREAD

**Issue by kavim** [especializati/setup-docker-laravel#1]
Senhores, ao tentar rodar `docker compose up -d` eu recebi o seguinte erro: 
`Error response from daemon: path /home/kavim/Projects/laravel/docker/nginx is mounted on / but it is not a shared mount.`

Utilizando o Composer 2 no WSL (debian) eu consegui resolver (depois pesquisar um pouco) com base  [nesse comentário](https://github.com/docker/compose/issues/8558#issuecomment-932766643)

basicamente removendo a ultima barra em  `./docker/nginx/:/etc/nginx/conf.d/`

```
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8989:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
        networks:
            - cursos
```
